// Pure renderer for src/lib/catalog/canon-profiles.ts (Session 3 §2.3). No I/O, no imports
// from the generated file: the same entries in any order give a byte-identical string.

import type { ItemProfile } from "@/lib/types";
import { stableJson } from "./profiling-run";

export type RenderMeta = {
  provider: string;
  model: string;
  profileVersion: string;
  vocabularyVersion: string;
  promptHash: string;
  generatedAt: string;
  total: number;
  failed: string[];
};

export function renderCanonProfilesModule(
  entries: Array<{ slug: string; profile: ItemProfile }>,
  meta: RenderMeta,
): string {
  const sorted = [...entries].sort((a, b) => a.slug.localeCompare(b.slug));
  const map: Record<string, ItemProfile> = {};
  for (const { slug, profile } of sorted) map[slug] = profile;

  const header = [
    "// GENERATED by scripts/profile-canon.ts — do not edit by hand.",
    `// provider: ${meta.provider}`,
    `// model: ${meta.model}`,
    `// profileVersion: ${meta.profileVersion}`,
    `// vocabularyVersion: ${meta.vocabularyVersion}`,
    `// promptHash: ${meta.promptHash}`,
    `// generatedAt: ${meta.generatedAt}`,
    `// total: ${meta.total}`,
    `// failed: ${meta.failed.length === 0 ? "(none)" : meta.failed.join(", ")}`,
  ].join("\n");

  return `${header}\n\nimport type { ItemProfile } from "@/lib/types";\n\nexport const CANON_PROFILES: Readonly<Record<string, ItemProfile>> = ${stableJson(map)}`;
}
