import { describe, expect, it } from "vitest";
import { CANON_BY_SLUG } from "@/lib/catalog/canon-data";
import { CANON_PROFILES } from "@/lib/catalog/canon-profiles";
import { canonProfile } from "@/lib/catalog/canon";
import { PROFILE_CAPS } from "@/lib/ai/profile-contract";
import { renderCanonProfilesModule } from "@/lib/dev/canon-profiles-render";
import { PROFILE_VERSION } from "@/lib/taste/weights";
import { band, minutesToFinish } from "@/lib/taste/form";
import { familyOf, isCraftKey } from "@/lib/taste/vocabulary";
import { canonToResult } from "@/lib/catalog/canon";
import type { ItemProfile } from "@/lib/types";

const profileOf = (): ItemProfile => ({
  profile_version: "p1",
  vocabulary_version: "v2",
  premise: "A test premise.",
  story: [{ key: "theme.grief", weight: 0.8, confidence: 0.9, source: "ai" }],
  feeling: [{ key: "tone.bleak", weight: 0.7, confidence: 0.8, source: "ai" }],
  form: { minutes_to_finish: 100, band: 1, craft: [] },
  vector: { story: { "theme.grief": 0.72 }, feeling: { "tone.bleak": 0.56 } },
});

describe("renderCanonProfilesModule (test H)", () => {
  const meta = {
    provider: "nvidia", model: "m1", profileVersion: "p1", vocabularyVersion: "v2",
    promptHash: "abcdef012345", generatedAt: "2026-09-22T00:00:00.000Z", total: 2, failed: ["book-zzz"],
  };
  const entries = [{ slug: "b-two", profile: profileOf() }, { slug: "a-one", profile: profileOf() }];

  it("is byte-identical for shuffled input and lists failed slugs in the header", () => {
    const one = renderCanonProfilesModule(entries, meta);
    const two = renderCanonProfilesModule([...entries].reverse(), meta);
    expect(one).toBe(two);
    expect(one.startsWith("// GENERATED by scripts/profile-canon.ts — do not edit by hand.")).toBe(true);
    expect(one).toContain("book-zzz");
    expect(one).toContain("generatedAt: 2026-09-22T00:00:00.000Z");
  });
  it("embeds deep-equal JSON with sorted slugs and a trailing newline", () => {
    const out = renderCanonProfilesModule(entries, meta);
    expect(out.endsWith("\n")).toBe(true);
    // The JSON object starts after `= ` and runs to the end (minus the trailing newline).
    const json = out.slice(out.indexOf("= ") + 2).replace(/\n$/, "");
    const parsed = JSON.parse(json) as Record<string, unknown>;
    expect(Object.keys(parsed)).toEqual(["a-one", "b-two"]); // sorted
    expect(parsed["a-one"]).toEqual(profileOf());
  });
  it("renders an empty module before the first live run", () => {
    const out = renderCanonProfilesModule([], { ...meta, total: 0, failed: [] });
    expect(out).toContain("CANON_PROFILES");
    expect(out).toContain("total: 0");
  });
});

describe("committed canon-profiles.ts integrity (test I)", () => {
  const slugs = Object.keys(CANON_PROFILES);

  it("every profiled slug exists in CANON", () => {
    for (const slug of slugs) expect(CANON_BY_SLUG.has(slug)).toBe(true);
  });

  it("versions are current", () => {
    for (const slug of slugs) {
      const p = CANON_PROFILES[slug];
      expect(p.profile_version).toBe(PROFILE_VERSION);
      expect(p.vocabulary_version).toBe("v2");
    }
  });

  it("every story/feeling key has the right family, the vector is well-formed and matches round4(w×c) ≥ 0.05", () => {
    for (const slug of slugs) {
      const p = CANON_PROFILES[slug];
      for (const a of [...p.story, ...p.feeling]) {
        const family = p.story.includes(a) ? "story" : "feeling";
        expect(familyOf(a.key)).toBe(family);
      }
      for (const family of ["story", "feeling"] as const) {
        for (const [key, value] of Object.entries(p.vector[family])) {
          expect(value).toBeGreaterThanOrEqual(0);
          expect(value).toBeLessThanOrEqual(1);
          const attr = [...p.story, ...p.feeling].find((a) => a.key === key);
          expect(attr).toBeDefined();
          if (attr) {
            expect(value).toBe(Math.round(attr.weight * attr.confidence * 10_000) / 10_000);
            expect(attr.weight * attr.confidence).toBeGreaterThanOrEqual(0.05);
          }
        }
      }
      // Craft never enters the vector.
      for (const c of p.form.craft) {
        expect(p.vector.story[c.key]).toBeUndefined();
        expect(p.vector.feeling[c.key]).toBeUndefined();
      }
    }
  });

  it("strict completeness: exactly one stakes and one ending, all five scalars, form from metadata, music cap, craft keys, premise length", () => {
    for (const slug of slugs) {
      const p = CANON_PROFILES[slug];
      expect(p.story.filter((a) => a.key.startsWith("stakes."))).toHaveLength(1);
      expect(p.story.filter((a) => a.key.startsWith("ending."))).toHaveLength(1);
      for (const scalar of ["intensity", "ache", "pace", "moral-complexity", "complexity"]) {
        const found = [...p.story, ...p.feeling].filter((a) => a.key === scalar);
        expect(found).toHaveLength(1);
      }
      const item = { ...canonToResult(CANON_BY_SLUG.get(slug)!), id: `canon:${slug}`, feel_prior: null };
      expect(p.form.minutes_to_finish).toBe(minutesToFinish(item));
      expect(p.form.band).toBe(item.category === "music" ? null : band(item.category, p.form.minutes_to_finish));
      for (const c of p.form.craft) expect(isCraftKey(item.category, c.key)).toBe(true);
      for (const a of [...p.story, ...p.feeling]) {
        if (item.category === "music" && a.source === "ai") expect(a.confidence).toBeLessThanOrEqual(0.5);
      }
      if (p.premise !== null) expect(p.premise.length).toBeLessThanOrEqual(400);
      void PROFILE_CAPS;
    }
  });

  it("canonProfile returns the profile or null", () => {
    const first = slugs[0];
    if (first) expect(canonProfile(first)).toBe(CANON_PROFILES[first]);
    expect(canonProfile("not-a-slug")).toBeNull();
    void slugs;
  });
});
